"""initial_structured_data_tables

Revision ID: c7f58bece6cb
Revises: 
Create Date: 2026-08-13 19:30:17.202448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f58bece6cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resp_admission_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('seat_limit_per_batch', sa.String(length=50), nullable=True),
    sa.Column('batch_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('free_demo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_to_check_availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resp_availability_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('batch_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('one_to_one_tuition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_for_current_seat_availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resp_branches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('batch_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nearby_landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resp_courses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_class', sa.String(length=100), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('focus', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('batch_size', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('exams_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resp_courses_category'), 'resp_courses', ['category'], unique=False)
    op.create_table('resp_eligibility_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_policy', sa.Text(), nullable=False),
    sa.Column('admission_process', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('demo_class', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resp_fee_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('contact_for_fees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('general_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resp_program_eligibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=True),
    sa.Column('min_class', sa.String(length=50), nullable=False),
    sa.Column('max_class', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['resp_courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resp_program_eligibility_program_name'), 'resp_program_eligibility', ['program_name'], unique=False)
    op.create_table('resp_program_fees',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('fee', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resp_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resp_program_fees')
    op.drop_index(op.f('ix_resp_program_eligibility_program_name'), table_name='resp_program_eligibility')
    op.drop_table('resp_program_eligibility')
    op.drop_table('resp_fee_policies')
    op.drop_table('resp_eligibility_policies')
    op.drop_index(op.f('ix_resp_courses_category'), table_name='resp_courses')
    op.drop_table('resp_courses')
    op.drop_table('resp_branches')
    op.drop_table('resp_availability_info')
    op.drop_table('resp_admission_status')
    # ### end Alembic commands ###
